[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyausaxs"
authors = [
  { name="Kristian Lytje", email="kristian.lytje@uni-saarland.de" }
]
version = "1.0.9"
description = "An efficient small-angle Debye scattering calculator."
readme = "README.md"
license = "LGPL-3.0-or-later"
requires-python = ">=3.9"
dependencies = [
  "py-cpuinfo>=8.0.0",
  "numpy>=1.20.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/AUSAXS/pyAUSAXS"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyausaxs*"]

[tool.setuptools.package-data]
"pyausaxs" = ["LIBRARY_PLACEHOLDER"]

[tool.setuptools]
include-package-data = false
license-files = []

[project.entry-points."pyinstaller40"]
hook-dirs = "pyausaxs.__pyinstaller.pyinstaller:get_hook_dirs"